#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


# [*********]
# [AutoStart]
# [*********]
~/.config/scripts/autostart.sh &

bspc monitor -d 1 2 3 4 5 6 7
bspc config border_width         5
bspc config window_gap          5


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bscp config pointer_modifier shift
bscp config pointer_action1 move


bspc rule -a blueman-manager state=floating
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc pointer -g window_move
bspc pointer -g window_resize_corner