#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


# [*********]
# [AutoStart]
# [*********]
picom --no-fading-openclose &
nm-applet &
volctl &
nitrogen --restore &
lxsession &
~/.config/qtile/scripts/battery_low.sh &
~/.config/lemonbar/hide_lemonbar_on_fullscreen.sh &


bspc monitor -d 1 2 3 4 5 6 7
bspc config border_width         0
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a blueman-manager state=floating
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc pointer -g window_move
bspc pointer -g window_resize_corner