#!/bin/bash

# Update mirror list
sudo mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.old
echo "################################################################################
############## Arch Linux mirrorlist generated by Abhishek Mishra ##############
################################################################################

Server = https://mirror.osbeck.com/archlinux/\$repo/os/\$arch
Server = https://us.mirrors.cicku.me/archlinux/\$repo/os/\$arch
Server = https://america.mirror.pkgbuild.com/\$repo/os/\$arch
Server = https://md.mirrors.hacktegic.com/archlinux/\$repo/os/\$arch
Server = https://mirrors.qontinuum.space/archlinux/\$repo/os/\$arch
Server = https://mirror.tmmworkshop.com/archlinux/\$repo/os/\$arch
Server = https://mirror.qctronics.com/archlinux/\$repo/os/\$arch
Server = https://europe.mirror.pkgbuild.com/\$repo/os/\$arch
Server = https://mirror2.sl-chat.ru/archlinux/\$repo/os/\$arch
Server = https://archmirror.it/repos/\$repo/os/\$arch" | sudo tee /etc/

